language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script:
- sudo apt-get install jq
- ../scripts/travisTest.sh
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: N5tcPcqgz9pj8lM5cFxyvvP2g1QUbH0+OPD3UT8SsOP5tj85Ra/zcxsd9vrZN6f1ivyJv82YGBYt5LfZ6MUcJbmpFTGNwzWT6mfZXKn6QBHs97YFNaF5fsx6GiXXRfkG/RCyuMU1EBbKlHC2T/PM8fktVizsSIMpEtwEzStEv8rDGss1YB16mKDpKbuGTdTxybZg2K0Ly5mxxJM75kRw+N0r3IinWsAcYKpSZhLRjkIabnibwr7sXeFi6TPBvtth6SfVoxCwW9/N+sIcejc7V0tjJveXKyr21co/kqrPSaPQUMrDG0t/L/aCJmXLnxHTVY15zmjsF4CnNggej9i+5aigRcPdVfl7mKhOpDsFxU3fH2biggsiy0j99wXyZkR/Kx3kziK4MO6qnsW0zN/dC6im74Ii/athKpV/DT/n+8voW7WXM+TQF0H3LNVJyTkPq0ctkHQA8sP2IPkl6cB0TGrLH9tEfWLzFcx8wTO3rkmyaciPs+enKD6sUB89LyrHMuovHSjlEZ9rBhUyZjyf0o8xpKwVgKxKqWJJr3B2oYWDxyctNvrDrc5SYCViyIL3fFJpjhvE6xmrVzsAcPxETBKMoBU2z1srDijOouDa6BYoQc3fDBNdYp2wGh/Avz/QdqAWaqH9v31i5whTpLPZGKADcCu6E7YGM3kIwkpF1mE=
    on_success: never
    on_failure: always
branches:
  only:
  - master
